### ISSUE TITLE
Rendering query

### ISSUE THREAD

**Issue by DanAlvares** [mgechev/ngworld#3]
Hi

Awesome project! I know this is just a demo and not supported, but thought I would just ask if you knew why the grass and modules would not be rendering (only the sky). 

I thought it might be the structure of my app so i tried with a boilerplate angular-cli project and the same thing happens. I am using Angular 4.2.4 generated using the Angular CLI.

I inspected the elements and noticed the a-frame entities don't have positions 
`<a-entity ... width: -Infinity" position="NaN 0 NaN" ...></a-entity>`

![screen shot 2017-10-18 at 09 48 39](https://user-images.githubusercontent.com/3328294/31709769-e640ccca-b3ea-11e7-8a48-109191dfb907.png)

Thanks :)

**Comment by mgechev** [comment]
Try ng-xmas :-)
